### ISSUE TITLE
feat: add project configured cargo aliase for `cargo doc`

### ISSUE THREAD

**Issue by kazuk** [SpringQL/SpringQL#137]
**Is your feature request related to a problem? Please describe.**

- `cargo make doc`
- `cargo doc`

are builds deference option to build doc. 
`cargo doc --open` runs doc build and shows miss-configured documentation.

**Describe the solution you'd like**

 add `.cargo/config.toml`

```toml
[alias]
d = ["doc","--no-deps", "--all-features"]
```

 `cargo d` builds project configured documentation.
 and `cargo d --open` well works.

**Describe alternatives you've considered**

`cargo doc` don't have project configuration options.

**Comment by laysakura** [comment]
@kazuk Fine.

We should use `cargo d` here:

https://github.com/SpringQL/SpringQL/blob/main/Makefile.toml#L91
