### ISSUE TITLE
ci: ci / example-run test is flaky

### ISSUE THREAD

**Issue by kazuk** [SpringQL/SpringQL#140]
## Describe the bug

`ci / example-run` test failed.
https://github.com/SpringQL/SpringQL/runs/6430624091?check_suite_focus=true#step:10:205

## To Reproduce

run CI

## Additional context

I want to fix it when the cause is found and can be fixed.

**Comment by laysakura** [comment]
`bug:` is for issues **users** get affected.

I change this into `ci:`.

---
Also I will add issue templates for `ci:`, `refactor:`.
