### ISSUE TITLE
deadlink task fails with HTTP Error 429 

### ISSUE THREAD

**Issue by kazuk** [SpringQL/SpringQL#196]
some time deadlink task fail.

[example](https://github.com/SpringQL/SpringQL/runs/6909479279?check_suite_focus=true)
```
[Err ] ./pull_request_template.md (13, 44) => https://github.com/zeke/semantic-pull-requests. 429 - Too Many Requests
[ OK ] ./CHANGELOG.md (147, 70) => https://github.com/SpringQL/SpringQL/pull/62.
[Err ] ./CHANGELOG.md (199, 12) => https://github.com/SpringQL/SpringQL/compare/v0.10.0...v0.11.0. 429 - Too Many Requests
[ OK ] ./CHANGELOG.md (67, 46) => https://github.com/rhysd/actionlint.
[Err ] ./README.md (11, 83) => https://github.com/SpringQL/SpringQL/blob/master/LICENSE-APACHE. 429 - Too Many Requests
[Err ] ./CHANGELOG.md (216, 11) => https://github.com/SpringQL/SpringQL/releases/v0.1.0. 429 - Too Many Requests
```

may be fix with `--throttle` option

[Markup Link Checker Reference](https://github.com/becheran/mlc/blob/master/docs/reference.md)

**Comment by kazuk** [comment]
re-open for this log.

https://github.com/SpringQL/SpringQL/runs/6943627546?check_suite_focus=true#step:13:171
https://github.com/SpringQL/SpringQL/runs/6943627546?check_suite_focus=true#step:13:246

more throttle value need?

**Comment by TaKO8Ki** [comment]
Completed in #254
