### ISSUE TITLE
examples/in_vehicle_pipeline.rs fails due to HTTPS file download

### ISSUE THREAD

**Issue by laysakura** [SpringQL/SpringQL#204]
## Describe the bug

https://github.com/SpringQL/SpringQL/runs/6975714837?check_suite_focus=true#step:13:219

```
+ cargo run --example in_vehicle_pipeline
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/examples/in_vehicle_pipeline`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("raw.githubusercontent.com")), port: None, path: "/SpringQL/dataset/main/pseudo-in-vehicle/Engine-30sec.tsv", query: None, fragment: None }, source: hyper::Error(Connect, "invalid URL, scheme is not http") }', springql/examples/in_vehicle_pipeline.rs:35:48
```

## To Reproduce

```bash
cargo run --example in_vehicle_pipeline
```

### code snippet

examples/in_vehicle_pipeline.rs

## Expected behavior

https://github.com/SpringQL/SpringQL/runs/6963679614?check_suite_focus=true#step:13:236

### SpringQL

- springql-core: 80b79c409e3eb452fa1666ae8658d3bc10e8265d

### your machine

GitHub Actions

## Additional context

Maybe failing after https://github.com/SpringQL/SpringQL/pull/200 is merged.

**Comment by kazuk** [comment]
https connection needs `default-tls` feature of `reqwest` .

https://github.com/SpringQL/SpringQL/commit/73945846add429d44de9cf155d0ffa4edb46e45c
